export type Trainer = {
  id: string
  name: string
  specialisms: string[]
  location: string
  plan: 'standard' | 'premium'
  bio: string
  imageUrl: string
  yearsExperience: number
  qualifications: string[]
  courses: string[]
}

export const trainers: Trainer[] = [
  {
    id: '1',
    name: 'Dr. Sarah Mitchell',
    specialisms: ['Botox', 'Anti-Wrinkle'],
    location: 'London',
    plan: 'premium',
    bio: 'Award-winning practitioner with 12 years in medical aesthetics.',
    imageUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
    yearsExperience: 12,
    qualifications: ['MBBS', 'Diploma in Aesthetic Medicine', 'Level 7 Aesthetic Practitioner'],
    courses: ['1-Day Botox Foundation', 'Advanced Anti-Wrinkle Masterclass', 'Full Face Botox'],
  },
  {
    id: '2',
    name: 'Emma Clarke',
    specialisms: ['Dermal Fillers', 'Lip Enhancement'],
    location: 'Manchester',
    plan: 'premium',
    bio: 'Specialist in natural-look lip and facial volumising techniques.',
    imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
    yearsExperience: 8,
    qualifications: ['RGN (Registered General Nurse)', 'Level 7 Aesthetic Practitioner'],
    courses: ['Filler Foundation Course', 'Advanced Lip Filler Masterclass', 'Cheek & Jawline Filler'],
  },
  {
    id: '3',
    name: 'Dr. Priya Sharma',
    specialisms: ['PDO Threads', 'Microneedling'],
    location: 'London',
    plan: 'premium',
    bio: 'Pioneer in minimally invasive thread lifting for natural results.',
    imageUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
    yearsExperience: 10,
    qualifications: ['MBBS', 'Postgraduate Certificate in Aesthetic Medicine'],
    courses: ['PDO Thread Lifting Foundation', 'Advanced Thread Techniques', 'Microneedling Certification'],
  },
  {
    id: '4',
    name: 'Dr. Aisha Patel',
    specialisms: ['PDO Threads', 'Botox', 'Anti-Wrinkle'],
    location: 'Manchester',
    plan: 'premium',
    bio: 'Multi-award-winning trainer known for comprehensive, hands-on courses.',
    imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
    yearsExperience: 14,
    qualifications: ['MBBS', 'Level 7 Aesthetic Practitioner', 'Diploma in Aesthetic Medicine'],
    courses: ['Combined Botox & Filler Foundation', 'PDO Thread Masterclass', 'Anti-Wrinkle Injection Course'],
  },
  {
    id: '5',
    name: 'Dr. Victoria Chen',
    specialisms: ['Laser Treatments', 'Skin Rejuvenation'],
    location: 'London',
    plan: 'premium',
    bio: 'Laser specialist bringing clinical precision to aesthetic education.',
    imageUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
    yearsExperience: 9,
    qualifications: ['MBBS', 'Certificate in Laser Safety', 'Postgraduate Certificate in Aesthetic Medicine'],
    courses: ['Laser Skin Resurfacing', 'IPL Foundation Course', 'Advanced Laser Treatments'],
  },
  {
    id: '6',
    name: 'Sophie Reynolds',
    specialisms: ['Lip Enhancement', 'Dermal Fillers', 'Chemical Peels'],
    location: 'Birmingham',
    plan: 'premium',
    bio: 'Known for her artistic approach to lip augmentation and facial balancing.',
    imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
    yearsExperience: 7,
    qualifications: ['RGN (Registered General Nurse)', 'Level 7 Aesthetic Practitioner'],
    courses: ['Lip Filler Masterclass', 'Full Face Filler', 'Chemical Peel Foundation'],
  },
  {
    id: '7',
    name: 'Dr. Rebecca Stone',
    specialisms: ['PRP', 'Microneedling', 'Skin Rejuvenation'],
    location: 'Leeds',
    plan: 'premium',
    bio: 'Renowned for regenerative treatments and a skin health-first philosophy.',
    imageUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
    yearsExperience: 11,
    qualifications: ['MBBS', 'Diploma in Aesthetic Medicine'],
    courses: ['PRP Vampire Facial', 'Microneedling Certification', 'Advanced Skin Rejuvenation'],
  },
  {
    id: '8',
    name: 'Dr. Charlotte Howe',
    specialisms: ['Fat Dissolving', 'Dermal Fillers'],
    location: 'Edinburgh',
    plan: 'premium',
    bio: 'Body contouring expert combining fillers and sculpting techniques.',
    imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
    yearsExperience: 6,
    qualifications: ['MBBS', 'Level 7 Aesthetic Practitioner'],
    courses: ['Fat Dissolving (Aqualyx) Foundation', 'Body Contouring Masterclass'],
  },
  {
    id: '9',
    name: 'Dr. Amara Okonkwo',
    specialisms: ['Botox', 'PDO Threads', 'IV Therapy'],
    location: 'London',
    plan: 'premium',
    bio: 'Holistic aesthetic medicine practitioner with a science-led teaching style.',
    imageUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
    yearsExperience: 13,
    qualifications: ['MBBS', 'Diploma in Aesthetic Medicine', 'IV Therapy Certification'],
    courses: ['Botox Foundation', 'IV Vitamin Therapy', 'Combined Aesthetics & Wellness'],
  },
  {
    id: '10',
    name: 'Isabelle Laurent',
    specialisms: ['Semi-Permanent Makeup', 'Lip Enhancement'],
    location: 'Bristol',
    plan: 'premium',
    bio: 'Brow and lip artist with a decade of permanent makeup mastery.',
    imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
    yearsExperience: 10,
    qualifications: ['VTCT Level 4 Beauty Therapy', 'SPMU Diploma', 'Level 7 Aesthetic Practitioner'],
    courses: ['Microblading Foundation', 'Ombre Brows Masterclass', 'Lip Blush Training'],
  },
  {
    id: '11',
    name: 'Dr. Hannah Pierce',
    specialisms: ['Laser Treatments', 'Chemical Peels'],
    location: 'Glasgow',
    plan: 'premium',
    bio: 'Dermatology-trained educator focusing on advanced skin correction.',
    imageUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
    yearsExperience: 15,
    qualifications: ['MBBS', 'Postgraduate Diploma in Dermatology', 'Laser Safety Certificate'],
    courses: ['Chemical Peel Masterclass', 'Laser Hair Removal', 'Advanced Skin Correction'],
  },
  {
    id: '12',
    name: 'Dr. Maya Singh',
    specialisms: ['Botox', 'Anti-Wrinkle', 'Dermal Fillers'],
    location: 'Liverpool',
    plan: 'premium',
    bio: 'Results-driven practitioner with a focus on natural, refreshed outcomes.',
    imageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    yearsExperience: 9,
    qualifications: ['MBBS', 'Level 7 Aesthetic Practitioner'],
    courses: ['Anti-Wrinkle Foundation', 'Dermal Filler Foundation', 'Combined Full Face Course'],
  },
  {
    id: '13',
    name: 'Dr. Claire Donnelly',
    specialisms: ['PDO Threads', 'PRP'],
    location: 'Cardiff',
    plan: 'premium',
    bio: 'Regenerative aesthetics specialist passionate about non-surgical lifting.',
    imageUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
    yearsExperience: 8,
    qualifications: ['MBBS', 'Diploma in Aesthetic Medicine'],
    courses: ['Thread Lift Foundation', 'PRP Masterclass', 'Non-Surgical Facelift'],
  },
  {
    id: '14',
    name: 'Olivia Hartley',
    specialisms: ['Dermal Fillers', 'Lip Enhancement', 'Microneedling'],
    location: 'Sheffield',
    plan: 'premium',
    bio: 'Creative injector and educator championing safe, beautiful results.',
    imageUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
    yearsExperience: 6,
    qualifications: ['RGN (Registered General Nurse)', 'Level 7 Aesthetic Practitioner'],
    courses: ['Lip Filler Foundation', 'Cheek Augmentation', 'Microneedling for Beginners'],
  },
  {
    id: '15',
    name: 'Dr. Natasha Bergmann',
    specialisms: ['Cryotherapy', 'Skin Rejuvenation'],
    location: 'London',
    plan: 'premium',
    bio: 'Skin longevity expert integrating cutting-edge cryotherapy protocols.',
    imageUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
    yearsExperience: 7,
    qualifications: ['MBBS', 'Postgraduate Certificate in Aesthetic Medicine'],
    courses: ['Cryotherapy Foundation', 'Skin Health Masterclass', 'Advanced Rejuvenation Protocols'],
  },
  {
    id: '16',
    name: 'James Thornton',
    specialisms: ['Skin Rejuvenation', 'Chemical Peels'],
    location: 'Birmingham',
    plan: 'standard',
    bio: 'Focused on skin health and evidence-based rejuvenation protocols.',
    imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    yearsExperience: 5,
    qualifications: ['BTEC Level 3 Beauty Therapy', 'Level 4 Aesthetics'],
    courses: ['Chemical Peel Foundation', 'Skin Analysis & Consultation'],
  },
  {
    id: '17',
    name: 'Natalie Brooks',
    specialisms: ['Lip Enhancement', 'Dermal Fillers'],
    location: 'Bristol',
    plan: 'standard',
    bio: 'Passionate about education-first aesthetics training.',
    imageUrl: 'https://randomuser.me/api/portraits/women/16.jpg',
    yearsExperience: 4,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Lip Filler Foundation', 'Nasolabial Folds & Marionette Lines'],
  },
  {
    id: '18',
    name: 'Dr. Fiona Walsh',
    specialisms: ['Botox', 'Skin Rejuvenation'],
    location: 'Leeds',
    plan: 'standard',
    bio: 'GP-trained aesthetician with a safety-led teaching approach.',
    imageUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
    yearsExperience: 7,
    qualifications: ['MBBS', 'MRCGP'],
    courses: ['Botox Foundation', 'Safe Injecting Masterclass'],
  },
  {
    id: '19',
    name: 'Marcus Reid',
    specialisms: ['Microneedling', 'Chemical Peels'],
    location: 'Edinburgh',
    plan: 'standard',
    bio: 'Skin science expert specialising in advanced resurfacing treatments.',
    imageUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
    yearsExperience: 6,
    qualifications: ['HNC Beauty Therapy', 'Level 4 Aesthetics', 'ITEC Level 3'],
    courses: ['Microneedling Foundation', 'Peel Protocols for Beginners'],
  },
  {
    id: '20',
    name: 'Tom Hargreaves',
    specialisms: ['Fat Dissolving', 'Cryotherapy'],
    location: 'Manchester',
    plan: 'standard',
    bio: 'Body treatment specialist with a growing reputation for sculpting results.',
    imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    yearsExperience: 4,
    qualifications: ['Level 4 Aesthetics', 'BTEC Level 3 Beauty Therapy'],
    courses: ['Fat Dissolving Foundation', 'Body Sculpting Basics'],
  },
  {
    id: '21',
    name: 'Lucy Pemberton',
    specialisms: ['Semi-Permanent Makeup'],
    location: 'London',
    plan: 'standard',
    bio: 'Dedicated brow artist and semi-permanent makeup trainer.',
    imageUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
    yearsExperience: 5,
    qualifications: ['VTCT Level 4 Beauty Therapy', 'SPMU Diploma'],
    courses: ['Microblading Foundation', 'Powder Brow Training'],
  },
  {
    id: '22',
    name: 'Dr. Andrew Kim',
    specialisms: ['Botox', 'Anti-Wrinkle'],
    location: 'Nottingham',
    plan: 'standard',
    bio: 'Methodical clinician with a reputation for thorough foundational training.',
    imageUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
    yearsExperience: 8,
    qualifications: ['MBBS', 'MRCGP'],
    courses: ['Anti-Wrinkle Foundation', 'Forehead & Brow Botox'],
  },
  {
    id: '23',
    name: 'Zoe Griffiths',
    specialisms: ['Dermal Fillers', 'Lip Enhancement'],
    location: 'Brighton',
    plan: 'standard',
    bio: 'Known for her warm teaching style and attention to natural outcomes.',
    imageUrl: 'https://randomuser.me/api/portraits/women/19.jpg',
    yearsExperience: 3,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Lip Filler Foundation', 'Tear Trough & Under-Eye Filler'],
  },
  {
    id: '24',
    name: 'Dr. Patrick Osei',
    specialisms: ['PRP', 'Microneedling'],
    location: 'London',
    plan: 'standard',
    bio: 'Regenerative medicine enthusiast bringing hospital-grade training to aesthetics.',
    imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
    yearsExperience: 6,
    qualifications: ['MBBS', 'Diploma in Aesthetic Medicine'],
    courses: ['PRP Hair Restoration', 'PRP Facial Foundation', 'Microneedling & PRP Combined'],
  },
  {
    id: '25',
    name: 'Jennifer Blake',
    specialisms: ['Chemical Peels', 'Skin Rejuvenation'],
    location: 'Oxford',
    plan: 'standard',
    bio: 'Evidence-based skin therapist with a passion for transformative peels.',
    imageUrl: 'https://randomuser.me/api/portraits/women/20.jpg',
    yearsExperience: 5,
    qualifications: ['BTEC Level 3 Beauty Therapy', 'Level 4 Aesthetics'],
    courses: ['Medium-Depth Peel Training', 'Skin Rejuvenation Protocols'],
  },
  {
    id: '26',
    name: 'Ryan Cooper',
    specialisms: ['Botox', 'Anti-Wrinkle', 'Dermal Fillers'],
    location: 'London',
    plan: 'standard',
    bio: 'Building a reputation for precise, safe injecting with great patient outcomes.',
    imageUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
    yearsExperience: 4,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Botox & Filler Foundation', 'Advanced Injectables Day'],
  },
  {
    id: '27',
    name: 'Sarah Yates',
    specialisms: ['Lip Enhancement', 'PDO Threads'],
    location: 'Cambridge',
    plan: 'standard',
    bio: 'Precise and patient trainer with expertise in lip anatomy and thread placement.',
    imageUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
    yearsExperience: 5,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Lip Filler Foundation', 'Mono Thread Introduction'],
  },
  {
    id: '28',
    name: 'Dr. Liam Fletcher',
    specialisms: ['Fat Dissolving', 'IV Therapy'],
    location: 'Glasgow',
    plan: 'standard',
    bio: 'Medical professional bridging wellness and aesthetic medicine.',
    imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
    yearsExperience: 7,
    qualifications: ['MBBS', 'IV Therapy Certification'],
    courses: ['Fat Dissolving Foundation', 'IV Vitamin Drip Training'],
  },
  {
    id: '29',
    name: 'Katie Morrison',
    specialisms: ['Microneedling', 'PRP'],
    location: 'Bath',
    plan: 'standard',
    bio: 'Skin specialist combining microneedling and PRP for maximum regenerative results.',
    imageUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
    yearsExperience: 4,
    qualifications: ['BTEC Level 3 Beauty Therapy', 'Level 4 Aesthetics'],
    courses: ['Microneedling Foundation', 'PRP Add-On Training'],
  },
  {
    id: '30',
    name: 'Daniel Park',
    specialisms: ['Semi-Permanent Makeup', 'Skin Rejuvenation'],
    location: 'London',
    plan: 'standard',
    bio: 'Creative professional with dual expertise in SPMU and skin treatments.',
    imageUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
    yearsExperience: 6,
    qualifications: ['HNC Beauty Therapy', 'SPMU Diploma'],
    courses: ['Ombre Brows', 'Nano Brow Training', 'Skin Booster Introduction'],
  },
  {
    id: '31',
    name: 'Rebecca Donovan',
    specialisms: ['Botox', 'Chemical Peels'],
    location: 'Sheffield',
    plan: 'standard',
    bio: 'Approachable trainer making aesthetic education accessible to all healthcare workers.',
    imageUrl: 'https://randomuser.me/api/portraits/women/23.jpg',
    yearsExperience: 5,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Botox Foundation', 'Chemical Peel Basics'],
  },
  {
    id: '32',
    name: 'Michael Turner',
    specialisms: ['Dermal Fillers', 'Fat Dissolving'],
    location: 'Bristol',
    plan: 'standard',
    bio: 'Practical injector-trainer focused on anatomy-led safe practice.',
    imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
    yearsExperience: 5,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Dermal Filler Foundation', 'Fat Dissolving (Aqualyx) Training'],
  },
  {
    id: '33',
    name: 'Anna Kovalenko',
    specialisms: ['PDO Threads', 'Skin Rejuvenation'],
    location: 'Manchester',
    plan: 'standard',
    bio: 'Thread lifting specialist with a European-trained precision approach.',
    imageUrl: 'https://randomuser.me/api/portraits/women/24.jpg',
    yearsExperience: 6,
    qualifications: ['Level 7 Aesthetic Practitioner', 'ITEC Level 3'],
    courses: ['PDO Thread Introduction', 'Skin Booster & Rejuvenation'],
  },
  {
    id: '34',
    name: 'Dr. Ben Harley',
    specialisms: ['Laser Treatments', 'Cryotherapy'],
    location: 'Edinburgh',
    plan: 'standard',
    bio: 'Technology-focused clinician keeping practitioners at the forefront of device-based aesthetics.',
    imageUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
    yearsExperience: 9,
    qualifications: ['MBBS', 'Laser Safety Certificate'],
    courses: ['Laser Foundation Course', 'Cryotherapy Skin Tag & Lesion Removal'],
  },
  {
    id: '35',
    name: 'Grace Thompson',
    specialisms: ['Lip Enhancement', 'Microneedling', 'PRP'],
    location: 'Liverpool',
    plan: 'standard',
    bio: 'Energetic trainer combining injectables knowledge with regenerative techniques.',
    imageUrl: 'https://randomuser.me/api/portraits/women/25.jpg',
    yearsExperience: 4,
    qualifications: ['RGN (Registered General Nurse)', 'Level 4 Aesthetics'],
    courses: ['Lip Filler Foundation', 'Microneedling Basics', 'PRP Introduction'],
  },
]

export const SPECIALISMS = Array.from(
  new Set(trainers.flatMap((t) => t.specialisms))
).sort()

export const LOCATIONS = Array.from(
  new Set(trainers.map((t) => t.location))
).sort()
